#custom Application Server port
server:
  port: 8081
  servlet:
    context-path: /carsapp

#Postgres DataBase Configuration
spring:
  config:
    activate:
      on-profile: default
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password:
    #jdbcUrl: jdbc:postgresql://ep-winter-moon-a59f5ymi-pooler.us-east-2.aws.neon.tech/neondb
    #username: neondb_owner
    #password: npg_rq9vIOac0TjP
    type: com.zaxxer.hikari.HikariDataSource
    # Hikari
    poolName: SpringBootHikariCP
    maximumPoolSize: 5
    minimumIdle: 3
    maxLifetime: 2000000
    connectionTimeout: 30000
    idleTimeout: 30000
    pool-prepared-statements: true


#Logger Configuration
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.rocky: DEBUG
  file:
    name: app.log
    path: logs
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"